### PR TITLE
pop seems to work.

### PR DESCRIPTION
**Pull request by uatach**
I've managed to make things work.

### CODE REVIEW

**Comment by Kerollmops** [comment]
I can't accept that the user need to implement the `Clone` trait, I think it's not mandatory to use this RandomWheel...
Sorry

**Comment by Kerollmops** [comment]
For example in the LinkedList I use, they don't need the `Clone` trait or `Box<T>`.
https://github.com/contain-rs/linked-list/blob/master/src/lib.rs

**Comment by uatach** [comment]
Yeah, I don't like the `Clone` either but I couldn't find another way.

**Comment by Kerollmops** [comment]
Yup I think we can use `VecDeque` collection ?
https://github.com/Kerosene2000/random-wheel-rs/issues/7#issuecomment-121201651

**Comment by Kerollmops** [comment]
But we can keep the test you do, that's good !

**Comment by Kerollmops** [comment]
Can you push, with a new pull request, the only tests please ?

**Pull request closed without merging**
